import Header from "../components/Header";
import "../styles/globals.css";
import AuthContext from "./context/AuthContext";
import { TokenProvider } from "./context/TokenContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="isaac-bg">
        <AuthContext>
          <TokenProvider>
            <main className=" max-w-7xl mx-auto">
              <Header />
              {children}
            </main>
          </TokenProvider>
        </AuthContext>
      </body>
    </html>
  );
}
