import Header from "../components/Header";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="isaac-bg">
        <main className=" max-w-7xl mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
